#This makefile prepares distribution-source from development-source
all:
#run "autoscan" and rename configure.scan to configure.in, or
#prepare configure.in
#prepare Makefile.am
#prepare NEWS, README, AUTHORS, ChangeLog
	-rm config.cache
	#aclocal -I /usr/share/aclocal/gnome2-macros #linux
	#aclocal -I /opt/local/share/aclocal #macports
	#aclocal -I /usr/local/share/aclocal #homebrew
	aclocal
	autoheader
	automake -c -a
	autoconf
